### ISSUE TITLE
v1.01 Checklist

### ISSUE THREAD

**Issue by dogtopus** [Project-Alpaca/Alpaca-OwO#1]
- [x] Move J2 and J3 1mm towards outside to get better connector mating
- [x] C10's trace width does not match the rest. Change it.
- [x] Recheck the push button switch footprint as it might not be the generic one
- [x] (Maybe) swap the inner 3V3 and GND plane so important parts will all sit directly on top of the GND plane
- [x] Possibly switch the 1V1 bridge to a inner plane for better inrush current capability
- [x] Too many changes to the component placement. Reroute everything.
- [x] PCBA planning (Priority: RP2040 and surrounding > smaller SMD components > bigger SMD components > THT components) (bonus mark for full JLCPCBA possibility. Fuse will be hard but with digikey ordering feature not impossible?)
- [x] Maybe also change the board to exact PS360 size?
- [x] ~~MadCatz Quick Connect port? (maybe need to move things around a bit. Routing-wise should have minimal problem if we can flip the J3 traces up)~~ Can be added but might needs to be vertically placed due to the current topology.

**Comment by dogtopus** [comment]
Bumped to v1.10 since it had more changes than initially planned.
